### ISSUE TITLE
Test run a chunk and batch - do they work with LOTUS?

### ISSUE THREAD

**Issue by agstephens** [cedadev/abcunit-cmip5-stats#37]
- [x] Test run a chunk
- [x] Test run a batch (on LOTUS)

Test run the examples in the `README.md` file:

```
python run_chunk.py -s mean -m MOHC/HadGEM2-ES -e r1i1p1
```

And

```
python run_batch.py -s mean -m MOHC/HadGEM2-ES
```

This should submit jobs to LOTUS.

Examine where the output and log files are being written.

**Comment by jhaigh0** [comment]
Tests `test_create_and_save_netcdf_file_input_as_dates` and `test_create_and_save_netcdf_file_input_as_dates_2` fail with error `TypeError: _generate_range() got an unexpected keyword argument 'dtype'` from `pd.date_range('1990-02-01', periods=5, dtype='datetime64[ns]', freq='M')})`
