### ISSUE TITLE
Migrate the `run_batch.py` script to use Slurm instead of LSF as the scheduler

### ISSUE THREAD

**Issue by agstephens** [cedadev/abcunit-cmip5-stats#38]
- [x] Read about using Slurm here: https://help.jasmin.ac.uk/category/4889-slurm
- [x] Read the quick guide to doing LSF to Slurm: https://help.jasmin.ac.uk/article/4891-lsf-to-slurm-quick-reference
- [x] Modify your fork to use Slurm and re-test that `run_batch.py` still runs and writes outputs where you expect them.

**Comment by jhaigh0** [comment]
Currently all ensembles output to .err with 
```
Traceback (most recent call last):
  File "/apps/slurm/spool/slurmd/job15192570/slurm_script", line 13, in <module>
    from lib import defaults
ModuleNotFoundError: No module named 'lib'
```
apparently the jaspy3.7 env doesn't have the lib module but not sure how installing stuff to it works

**Comment by agstephens** [comment]
There are a few things going on here:

1. Jaspy is the same across the `sci` and LOTUS nodes.
2. The `lib` module is local to the `abcunit...` package.
3. When you run tests locally you have run the `setup-env.sh` script to set your environment.
4. You need to run `setup-env.sh` locally (on `sci*`) before running the jobs on LOTUS - because it defines the environment you need.
