### ISSUE TITLE
Install Postgres on your Vagrant VM

### ISSUE THREAD

**Issue by agstephens** [cedadev/abcunit-cmip5-stats#41]
Install Postgresql on your Vagrant VM, the notes here give a short-cut on how to install:

https://github.com/agstephens/software-notes/tree/master/tools/postgresql

You only need to set up the server, get it running and then test it works:

```
su - postgres  # login as user "postgres"
psql  # Opens up an SQL terminal where you can run SQL commands
```

**Comment by jhaigh0** [comment]
on the command `psql -U mytest` from the link, I get  `psql: FATAL:  Peer authentication failed for user "mytest"`

Have been able to run commands 
```
su - postgres  # login as user "postgres"
psql  # Opens up an SQL terminal where you can run SQL commands
```
though.

**Comment by jhaigh0** [comment]
Now logged in as the vagrant user and `su - postgres` results in an authentication failure.

Tried to create a database this way,
```
(dbEnv) (base) [vagrant@localhost postgresThings]$ sudo -u postgres psql
could not change directory to "/home/vagrant/work/postgresThings"
psql (9.2.24)
Type "help" for help.

postgres=# create database mydatabase
postgres-# create user me with encrypted password 'mytestpassword'
postgres-# grant all privilleges on database mydatabase to me
postgres-# psql
```
but was pretty confused. thought `psql` would take me into sql terminal but just did nothing.

**Comment by agstephens** [comment]
@jhaigh0: I think that in your second example above - _you are already inside the SQL terminal_.

The top command is: `sudo -u postgres psql`

That means: "Run `psql` as the user `postgres`"

The `create database`, `create user` and `grant all` commands are all SQL. So you don't need the last `psql`.

...I think that is the issue anyway.
