### ISSUE TITLE
Please test out the database backend in abcunit

### ISSUE THREAD

**Issue by agstephens** [cedadev/abcunit-cmip5-stats#53]
@ellesmith88: @jhaigh0 has rewritten the backend that manages success and failure records in abcunit. Please can you follow the instructions in the README.md file to request a postgres database on JASMIN - and then use the "db" backend settings to run with abcunit. @jhaigh0 can advise if you need more info. Thanks

**Comment by ellesmith88** [comment]
Will do - database requested.

**Comment by agstephens** [comment]
Thanks @ellesmith88

**Comment by ellesmith88** [comment]
@jhaigh0 @agstephens I've been asked whether this should this be on the CEDA internal postgres database (on db3.ceda.ac.uk) or the Jasmin users postgres database (on udb1.jasmin.ac.uk). Does it matter where it is?

**Comment by jhaigh0** [comment]
@ellesmith88 The one I used was on udb1.jasmin.ac.uk so that should work

**Comment by ellesmith88** [comment]
I've tested this (after help from Jonathan) and it all looks great. @jhaigh0 I don't know whether it would be worth putting in the readme how to look at the results in the database?
